Rmi 2658 adf triggers
hmcts/mi-core-lib pull request #159
Opened 2023-02-13 14:24 UTC by HarrisonBoyleThomas

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RMI-2658

### Change description ###
Update the adf deployment to deactivate any active triggers, and reactivate them after deployment to prevent errors

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-02-14 09:47 UTC, tchow8 approved these changes

2023-02-14 09:54 UTC, qzhou-hmcts requested changes
This causes problems in STG and PROD deployment 
It was removed with the new ADF deployment plugin
https://github.com/hmcts/mi-core-lib/pull/121/files

2023-02-14 12:17 UTC, qzhou-hmcts approved these changes

2023-03-03 14:53 UTC, HarrisonBoyleThomas commented
New test run with triggers active
<img width="690" alt="Screenshot 2023-03-03 at 13 38 32" src="https://user-images.githubusercontent.com/55688012/222734230-c0468852-9100-4f45-9ecc-6eb6be3e3650.png">
https://dev.azure.com/hmcts/MI%20Reporting/_build/results?buildId=347507&view=results

2023-03-03 15:00 UTC, tchow8 approved these changes

2023-03-06 14:00 UTC, qzhou-hmcts approved these changes

2023-03-07 13:35 UTC, merged